// ============ MT_BAG SPECIFIC VARIABLES ============
export const MT_FRONT_DESIGN_FOOD = [
  '"PREMIUM ROASTED SEAWEED" branding, appetizing photography of seaweed slices with sesame oil, and gold accents on a dark green background',
  '"CRISPY DRIED SQUID" branding, golden dried squid illustration with red chili accents on a navy blue background',
  '"SAVORY BEEF JERKY" branding, smoky meat texture photography with flame effects on a rustic brown background',
  '"CLASSIC KIMCHI" branding, vibrant red fermented cabbage imagery with traditional Korean patterns on white',
  '"OCEAN DRIED FISH" branding, silver fish illustration with wave patterns on a deep blue background',
  '"PREMIUM NORI SHEETS" branding, elegant black seaweed texture with gold typography on dark green',
  '"SPICY ANCHOVY SNACK" branding, crispy anchovy photography with red pepper flakes on orange background',
  '"TRADITIONAL PICKLES" branding, colorful vegetable illustrations with vintage jar imagery on cream',
  '"GOURMET DRIED MANGO" branding, tropical mango slice photography with sunset gradients on yellow',
  '"ARTISAN TEMPEH" branding, organic soybean texture with earthy brown tones and green leaf accents',
];

export const MT_FRONT_DESIGN_BEAUTY = [
  '"PURE BABY WIPES" branding, soft pastel blue and white cloud illustrations, and a "Fragrance Free" emblem',
  '"GENTLE CLEANSING WIPES" branding, water droplet effects with mint green and white color scheme',
  '"MAKEUP REMOVER PADS" branding, elegant rose gold accents on soft pink background with cotton texture',
  '"SENSITIVE SKIN WIPES" branding, calming lavender color palette with delicate flower illustrations',
  '"REFRESHING FACE TOWELS" branding, cool ocean blue gradients with wave patterns and "Cooling Effect" badge',
  '"NATURAL COTTON PADS" branding, organic cotton plant illustrations on cream background with green accents',
  '"HYDRATING SHEET MASK" branding, dewy skin texture imagery with hyaluronic acid molecular design on white',
  '"EXFOLIATING PADS" branding, fresh citrus illustrations with vitamin C emblem on bright yellow background',
  '"SOOTHING ALOE WIPES" branding, green aloe vera plant imagery with water splash effects on mint background',
  '"LUXURY SPA TOWELS" branding, zen stone and bamboo illustrations with gold trim on charcoal background',
];

export const MT_BACK_DESIGN_FOOD = [
  'nutrition facts, a barcode, and ingredient list in clean layout',
  'nutritional information table, storage instructions, and manufacturer details',
  'calorie chart, allergen warnings, and best before date section',
  'serving suggestions, nutrition panel, and QR code for recipes',
  'detailed ingredients, dietary information icons, and origin label',
];

export const MT_BACK_DESIGN_BEAUTY = [
  'usage instructions, ingredients list, and safety warnings',
  'how to use steps, key ingredients highlight, and dermatologist tested badge',
  'application guide, full ingredient list, and recycling symbols',
  'directions for use, active ingredients panel, and contact information',
  'step-by-step usage icons, formula benefits, and certification logos',
];

export const MT_TEXTURE = [
  'glossy plastic film',
  'smooth matte soft-touch',
  'metallic foil shimmer',
  'pearlescent sheen',
  'semi-gloss laminated',
  'brushed satin',
  'holographic accent',
  'velvet soft-touch',
  'kraft paper textured',
  'frosted matte',
];

export const MT_CONTENT_TYPE_FOOD = [
  'seasoned seaweed',
  'dried squid snack',
  'beef jerky',
  'kimchi',
  'dried fish',
  'pickled vegetables',
  'dried mango slices',
  'fermented soybeans',
];

export const MT_CONTENT_TYPE_BEAUTY = [
  'wet wipes',
  'baby wipes',
  'cleansing pads',
  'makeup remover wipes',
  'face towels',
  'cotton pads',
  'sheet masks',
  'exfoliating pads',
];

export const DESIGN_THEME_AND_GRAPHICS = [
  'minimalist line art with botanical elements',
  'bold geometric patterns with gradient fill',
  'hand-drawn illustrations with organic shapes',
  'vintage typography with retro ornaments',
  'modern abstract shapes with vibrant colors',
  'elegant floral motifs with gold accents',
  'playful cartoon characters with bright palette',
  'clean corporate design with subtle textures',
  'artistic watercolor splashes with soft edges',
  'futuristic tech-inspired circuit patterns',
  'nature-inspired leaf and vine decorations',
  'traditional ethnic patterns with rich details',
  'pop art style with halftone dots',
  'luxury marble texture with metallic foil',
  'kawaii cute style with pastel colors',
  'grunge distressed look with bold type',
  'art deco geometric with golden lines',
  'scandinavian minimal with muted tones',
  'tropical paradise with exotic fruits',
  'zen japanese style with ink brush strokes',
  'sports dynamic with motion blur effects',
  'farm fresh rustic with kraft texture',
  'space galaxy theme with cosmic colors',
  'ocean wave patterns with blue gradients',
  'mountain landscape with earth tones',
  'urban street art with spray paint effects',
  'elegant calligraphy with script fonts',
  'tech startup modern with flat icons',
  'vintage pharmacy with apothecary style',
  'wellness spa with zen garden elements',
  'fitness energy with lightning bolts',
  'kids playful with rainbow colors',
  'eco friendly with recycled paper look',
  'premium gold emboss with black background',
  'christmas festive with holiday patterns',
  'summer beach with tropical vibes',
  'autumn harvest with warm colors',
  'spring bloom with flower illustrations',
  'winter frost with icy blue tones',
  'coffee shop aesthetic with bean motifs',
];

export const ZIPPER_TYPE = [
  'resealable zipper line at top',
  'press-to-close zipper seal',
  'slider zipper mechanism',
  'tear notch with no zipper',
  'velcro-style closure',
  'fold-over tin tie closure',
  'ziplock reclosable top',
  'easy-open tear strip',
  'peel and reseal adhesive',
  'double zipper for freshness',
  'child-resistant zipper',
  'tamper-evident seal band',
  'magnetic closure strip',
  'snap-lock zipper',
  'grip seal closure',
  'euro slot with zipper',
  'spout cap with zipper',
  'twist tie closure',
  'heat seal only no zipper',
  'reinforced heavy-duty zipper',
];

// ============ CATEGORY TYPE ============
// 환경변수로 카테고리 전환: CATEGORY_TYPE=food 또는 CATEGORY_TYPE=beauty
export type CategoryType = 'food' | 'beauty';
export const CATEGORY_TYPE: CategoryType =
  (process.env.CATEGORY_TYPE as CategoryType) ?? 'food';

// ============ FOOD CATEGORY ============
// mask 템플릿 전용: 발효/가공식품
export const PRODUCT_CATEGORY_FOOD_MASK = [
  // 육포/건조육류
  'beef jerky',
  'pork jerky',
  'chicken jerky',
  'turkey jerky',
  'venison jerky',
  'biltong dried meat',
  'dried beef strips',
  'smoked meat snack',
  'peppered beef jerky',
  'teriyaki beef jerky',
  'spicy pork jerky',
  'honey glazed jerky',
  'BBQ flavored jerky',
  'garlic beef jerky',
  'original dried meat',
  // 김치/발효채소
  'kimchi',
  'aged kimchi',
  'cabbage kimchi',
  'radish kimchi',
  'cucumber kimchi',
  'green onion kimchi',
  'fermented vegetables',
  'pickled radish',
  'pickled cucumber',
  'pickled garlic',
  'sauerkraut',
  'pickled cabbage',
  'fermented bean paste',
  'doenjang paste',
  'gochujang paste',
  // 젓갈/해산물 발효
  'salted shrimp',
  'fermented fish',
  'anchovy sauce',
  'fish sauce',
  'salted pollack roe',
  'fermented squid',
  'salted crab',
  'oyster sauce',
  'fermented clam',
  'dried anchovy',
  'dried shrimp',
  // 건어물/해산물
  'dried squid',
  'dried filefish',
  'dried pollack',
  'dried cod',
  'dried yellow croaker',
  'dried cuttlefish',
  'seasoned dried squid',
  'roasted dried squid',
  'butter squid snack',
  'spicy dried squid',
  'fish jerky',
  'dried octopus',
  'dried scallop',
  'dried abalone',
  // 장아찌/절임류
  'pickled garlic',
  'pickled pepper',
  'pickled onion',
  'pickled ginger',
  'pickled plum',
  'pickled perilla leaves',
  'soy pickled vegetables',
  'vinegar pickles',
  'sweet pickled radish',
  'pickled lotus root',
  'pickled burdock',
  'pickled mushroom',
  // 가공육/소시지
  'smoked sausage',
  'dried sausage',
  'pepperoni',
  'salami slices',
  'ham slices',
  'bacon bits',
  'chorizo',
  'prosciutto',
  'meat snack stick',
  'summer sausage',
  // 전통 발효식품
  'fermented soybean',
  'natto beans',
  'tempeh',
  'miso paste',
  'fermented rice',
  'makgeolli powder',
  'nuruk ferment starter',
  'fermented black beans',
  'fermented tofu',
  'stinky tofu',
  // 건조과일/채소
  'dried mango',
  'dried banana',
  'dried pineapple',
  'dried apple',
  'dried persimmon',
  'dried jujube',
  'dried cranberries',
  'raisins',
  'dried apricots',
  'dried figs',
  'dried tomato',
  'dried mushroom',
  'dried seaweed',
  'roasted seaweed',
  'seasoned seaweed',
  'dried sweet potato',
  'dried radish',
  'dried chili pepper',
  'dried garlic',
  'dried ginger',
  'freeze dried fruit',
  'fruit chips',
  'vegetable chips',
  'dried kiwi',
  'dried strawberry',
  'dried blueberry',
  'dried coconut',
  'dried papaya',
  'dried pear',
  'dried orange',
  'dried lemon',
  'dried grapefruit',
];

// 일반 식품 (다른 템플릿용)
export const PRODUCT_CATEGORY_FOOD = [
  // 건조과일/채소
  'dried mango',
  'dried banana',
  'dried pineapple',
  'dried apple',
  'dried persimmon',
  'dried jujube',
  'dried cranberries',
  'raisins',
  'dried apricots',
  'dried figs',
  'dried tomato',
  'dried mushroom',
  'dried seaweed',
  'roasted seaweed',
  'seasoned seaweed',
  // 견과류
  'mixed nuts',
  'roasted almonds',
  'cashew nuts',
  'macadamia nuts',
  'pistachios',
  'walnuts',
  'peanuts',
  'honey roasted nuts',
  'wasabi peanuts',
  'spicy almonds',
  'trail mix',
  'seeds mix',
  'pumpkin seeds',
  'sunflower seeds',
  // 스낵/과자
  'rice crackers',
  'shrimp crackers',
  'vegetable chips',
  'seaweed snack',
  'rice cake snack',
  'corn snack',
  'potato chips',
  'pretzels',
  'popcorn',
  // 조미료/소스
  'seasoning powder',
  'spice mix',
  'curry powder',
  'chili flakes',
  'garlic powder',
  'onion powder',
  'soup powder',
  'bouillon cubes',
  'sauce packets',
  'soy sauce packets',
  // 차/음료
  'green tea',
  'black tea',
  'herbal tea',
  'instant coffee',
  'cocoa powder',
  'drink mix',
  // 건강식품
  'probiotics',
  'vitamin supplements',
  'protein powder',
  'collagen powder',
  // 면/즉석
  'instant noodles',
  'ramen',
  'udon noodles',
  'rice noodles',
  // 펫푸드
  'dog treats',
  'cat treats',
  'pet jerky',
];

export const PRODUCT_NAME_FOOD = [
  // 스낵/과자
  'CRUNCHY BITES',
  'SNACK TIME',
  'CRISPY JOY',
  'MUNCH BOX',
  'TASTY CRUNCH',
  'HAPPY SNACK',
  'YUMMY CHIPS',
  'DELISH',
  'CRUNCH MASTER',
  'SNACK ATTACK',
  // 음료/커피
  'MORNING BREW',
  'CAFÉ BLEND',
  'INSTANT JOY',
  'QUICK CUP',
  'FRESH ROAST',
  'BEAN DELIGHT',
  'TEA TIME',
  'SOOTHE',
  'REFRESH',
  'ENERGIZE',
  // 조미료/소스
  'FLAVOR KING',
  'TASTE BOOST',
  'SPICE MIX',
  'SEASON ALL',
  'ZESTY',
  'SAVORY',
  'UMAMI',
  'TANGY',
  // 면/즉석식품
  'QUICK MEAL',
  'EASY COOK',
  'INSTANT FEAST',
  'FAST BOWL',
  'HOT POT',
  'NOODLE JOY',
  // 건강식품
  'VITA PLUS',
  'HEALTH FIRST',
  'NUTRI CARE',
  'BODY FUEL',
  'FIT LIFE',
  'WELLNESS',
  'PURE LIFE',
  'BALANCE',
  // 견과류/건조식품
  'NUT HOUSE',
  'TRAIL MIX',
  'NATURE BITES',
  'FRUIT BURST',
  'SEED POWER',
  'DRIED GOLD',
  // 초콜릿/캔디
  'SWEET TREAT',
  'CHOCO LOVE',
  'CANDY POP',
  'SUGAR RUSH',
  'DELIGHT',
  'BLISS',
  // 일반
  'GOODNESS',
  'PRIME',
  'SELECT',
  'CHOICE',
  'CLASSIC',
  'PREMIUM',
  'GOLD',
  'BEST',
  'TOP PICK',
  'FAVORITE',
];

// ============ BEAUTY CATEGORY ============
export const PRODUCT_CATEGORY_BEAUTY = [
  'green tea extract skincare',
  'vitamin C brightening serum',
  'hyaluronic acid hydration',
  'charcoal deep cleansing',
  'rose petal moisturizing',
  'aloe vera soothing care',
  'collagen anti-aging treatment',
  'honey nourishing essence',
  'cucumber cooling relief',
  'lavender calming therapy',
  'snail mucin repair',
  'centella asiatica healing',
  'niacinamide pore care',
  'retinol night renewal',
  'tea tree acne control',
  'pearl brightening glow',
  'propolis barrier repair',
  'rice bran whitening',
  'bamboo detox purifying',
  'avocado deep nutrition',
  'coconut hydrating boost',
  'berry antioxidant shield',
  'ginseng revitalizing energy',
  'lotus flower radiance',
  'seaweed mineral infusion',
  'oat calming sensitive care',
  'shea butter intensive moisture',
  'papaya enzyme exfoliating',
  'pomegranate firming lift',
  'turmeric anti-inflammatory',
  'caffeine eye awakening',
  'sakura blossom renewal',
  'volcanic ash pore cleanse',
  'milk protein softening',
  'egg white pore tightening',
  'gold luxe anti-wrinkle',
  'platinum cell regeneration',
  'caviar premium nutrition',
  'truffle luxury repair',
  'diamond radiance boost',
  'matcha antioxidant fresh',
  'lemon vitamin refresh',
  'mango tropical hydration',
  'peach soft glow care',
  'grape seed anti-aging',
  'olive deep moisturizing',
  'jojoba oil balancing',
  'argan intensive repair',
  'macadamia silk smooth',
  'quinoa protein strengthen',
];

export const PRODUCT_NAME_BEAUTY = [
  'AQUA GLOW',
  'PURE BLOOM',
  'SKIN ELIXIR',
  'DEWDROP',
  'RADIANCE',
  'VELVET TOUCH',
  'HYDRA BOOST',
  'LUMINOUS',
  'FRESH START',
  'GLOW UP',
  'SILK VEIL',
  'CLARITY',
  'REVIVE',
  'RENEWAL',
  'ESSENCE',
  'VITAL CARE',
  'SOFT PETAL',
  'YOUTH DEW',
  'CLEAR SKIN',
  'MOISTURE LOCK',
  'BRIGHT DAYS',
  'CALM WAVE',
  'PURE TOUCH',
  'SKIN FOOD',
  'DEEP REPAIR',
  'FRESH FACE',
  'GLOW GETTER',
  'BEAUTY BOOST',
  'SKIN RESCUE',
  'HYDRA VEIL',
  'PURE AURA',
  'RADIANT YOU',
  'SKIN TREAT',
  'DAILY GLOW',
  'AQUA FRESH',
  'SOFT GLOW',
  'PORE CARE',
  'SKIN TONIC',
  'VITAL MIST',
  'CLEAR TONE',
  'BRIGHT AURA',
  'CALM CARE',
  'PURE SKIN',
  'GLOW RITUAL',
  'SKIN SAVER',
  'HYDRA LOVE',
  'FRESH GLOW',
  'BEAUTY VEIL',
  'SKIN BLISS',
  'PURE RADIANCE',
];

// ============ CATEGORY SELECTOR ============
export const PRODUCT_CATEGORY =
  CATEGORY_TYPE === 'food' ? PRODUCT_CATEGORY_FOOD : PRODUCT_CATEGORY_BEAUTY;

export const PRODUCT_NAME_BY_CATEGORY =
  CATEGORY_TYPE === 'food' ? PRODUCT_NAME_FOOD : PRODUCT_NAME_BEAUTY;

export const DESIGN_THEME_COLOR = [
  'earthy brown and cream',
  'vibrant orange and yellow',
  'deep navy and gold',
  'fresh mint and white',
  'bold red and black',
  'pastel pink and grey',
  'forest green and tan',
  'royal purple and silver',
  'sunset coral and peach',
  'arctic blue and white',
  'tropical teal and lime',
  'rustic terracotta and sage',
  'modern black and rose gold',
  'natural kraft and green',
  'berry purple and pink',
  'ocean blue and sand',
  'autumn orange and brown',
  'spring green and yellow',
  'winter white and silver',
  'summer coral and turquoise',
  'elegant champagne and ivory',
  'sporty red and grey',
  'zen white and bamboo',
  'retro mustard and teal',
  'luxe gold and black',
  'fresh lime and white',
  'warm caramel and cream',
  'cool grey and electric blue',
  'organic green and brown',
  'playful rainbow gradient',
  'minimalist white and black',
  'vintage sepia and cream',
  'neon pink and black',
  'earthy olive and rust',
  'sophisticated burgundy and gold',
  'cheerful yellow and white',
  'calming lavender and grey',
  'energetic orange and blue',
  'natural beige and forest',
  'premium matte black',
  'holographic silver',
  'gradient sunset tones',
  'monochrome grey scale',
  'duotone blue and orange',
  'pastel gradient blend',
  'jewel tone emerald',
  'dusty rose and marble',
  'copper and cream',
  'sage and terracotta',
  'indigo and gold',
];

export const TEXTURE_OR_FINISH = [
  'matte lamination finish',
  'glossy high-shine surface',
  'soft-touch velvet coating',
  'metallic foil accents',
  'kraft paper texture',
  'embossed logo detail',
  'spot UV highlights',
  'holographic elements',
  'brushed metal effect',
  'linen texture print',
  'clear window panel',
  'frosted matte section',
  'pearlescent shimmer',
  'debossed pattern',
  'glitter sparkle finish',
  'wood grain print',
  'marble pattern design',
  'concrete texture effect',
  'leather emboss look',
  'canvas fabric texture',
  'watercolor wash effect',
  'gradient fade finish',
  'geometric pattern emboss',
  'floral emboss detail',
  'minimalist clean finish',
  'vintage distressed look',
  'premium silk finish',
  'eco recycled texture',
  'bamboo fiber look',
  'stone texture print',
  'wave pattern design',
  'honeycomb geometric',
  'dot matrix pattern',
  'stripe accent design',
  'abstract art print',
  'botanical illustration',
  'hand-drawn sketch style',
  'photography print',
  'infographic design',
  'icon pattern repeat',
  'typography focused',
  'negative space design',
  'asymmetric layout',
  'centered composition',
  'diagonal stripe accent',
  'border frame design',
  'floating elements',
  'layered depth effect',
  'shadow detail finish',
  '3D emboss illusion',
];

export const COLOR_MOOD = [
  'pastel pink gradient',
  'mint green fresh',
  'lavender purple soft',
  'coral orange warm',
  'sky blue calming',
  'champagne gold luxury',
  'rose gold elegant',
  'forest green natural',
  'ocean blue deep',
  'sunset orange vibrant',
  'cherry blossom pink',
  'arctic white clean',
  'charcoal grey modern',
  'navy blue classic',
  'emerald green rich',
  'burgundy wine premium',
  'terracotta earth',
  'sage green organic',
  'dusty rose vintage',
  'cream beige neutral',
  'pearl white luminous',
  'blush pink delicate',
  'teal blue refreshing',
  'mustard yellow bold',
  'plum purple deep',
  'apricot peach soft',
  'turquoise tropical',
  'mauve sophisticated',
  'olive green earthy',
  'salmon pink warm',
  'ice blue cool',
  'honey gold warm',
  'lilac purple dreamy',
  'tangerine energetic',
  'slate grey minimal',
  'copper metallic',
  'bronze shimmer',
  'silver frost',
  'ruby red bold',
  'sapphire blue royal',
  'jade green serene',
  'ivory cream classic',
  'graphite dark modern',
  'lemon yellow bright',
  'watermelon pink fun',
  'avocado green fresh',
  'caramel brown warm',
  'cotton candy pastel',
  'holographic iridescent',
  'matte black sleek',
];

export const TEXTURE_OR_WINDOW = [
  'matte finish surface',
  'glossy reflective coating',
  'metallic foil accent',
  'holographic shimmer strip',
  'embossed logo pattern',
  'debossed texture detail',
  'soft touch velvet',
  'transparent window panel',
  'frosted translucent area',
  'kraft paper texture',
  'linen fabric feel',
  'silk smooth surface',
  'brushed metal effect',
  'crinkle foil texture',
  'pearlescent sheen',
  'rainbow gradient foil',
  'spot UV gloss detail',
  'matte lamination',
  'glitter sparkle finish',
  'suede soft coating',
  'marble pattern print',
  'wood grain texture',
  'concrete industrial feel',
  'leather emboss effect',
  'canvas fabric texture',
  'water droplet effect',
  'bubble texture pattern',
  'honeycomb geometric',
  'wave pattern emboss',
  'floral emboss detail',
  'geometric cut window',
  'oval clear window',
  'heart shape window',
  'star burst pattern',
  'dot matrix texture',
  'stripe pattern accent',
  'checkered design',
  'gradient fade effect',
  'ombre color blend',
  'tie dye swirl',
  'splatter art effect',
  'watercolor wash',
  'sketch line art',
  'botanical print',
  'minimal line design',
  'abstract geometric',
  'retro vintage style',
  'art deco pattern',
  'scandinavian minimal',
  'japanese zen style',
];

// ============ UNIFIED TEMPLATES ============
export const PROMPT_TEMPLATES: Record<string, string> = {
  '3side': `Flat rectangular foil packet, 3-side sealed, design theme is [PRODUCT_CATEGORY_MASK] packaging, [COLOR_MOOD] print, [TEXTURE_OR_WINDOW], all text must be in English only (no Korean, Chinese, or other non-English characters), product name "[PRODUCT_NAME]", top-down flat lay view, isolated on white background --no zipper, ziplock, cosmetic bottle, stand`,

  spout: `Stand-up pouch with a plastic spout nozzle cap on top center, liquid packaging structure, design theme is [PRODUCT_CATEGORY] packaging, [DESIGN_THEME_COLOR] color palette, [TEXTURE_OR_FINISH], all text must be in English only (no Korean, Chinese, or other non-English characters), product name "[PRODUCT_NAME]", professional studio lighting, 8k resolution, photorealistic, isolated on white background --ar 4:5 --no zipper, solid food, box shape`,

  mbag: `Side gusset pouch, tall block bottom bag, thick side profile with M-fold, brick shape structure, standing upright, design theme is [PRODUCT_CATEGORY] packaging, [DESIGN_THEME_COLOR] color palette, [TEXTURE_OR_FINISH], all text must be in English only (no Korean, Chinese, or other non-English characters), product name "[PRODUCT_NAME]", professional studio lighting, 8k resolution, photorealistic, isolated on white background --ar 4:5 --no zipper, doypack, tapered bottom`,

  mbag_slim: `Tall and narrow Side gusset pouch, slender brick shape, elongated vertical structure (approx 1:2.5 ratio), M-fold side panels clearly visible, standing upright, design theme is [PRODUCT_CATEGORY] packaging, [DESIGN_THEME_COLOR] color palette, [TEXTURE_OR_FINISH], all text must be in English only (no Korean, Chinese, or other non-English characters), product name "[PRODUCT_NAME]", professional studio lighting, 8k resolution, photorealistic, isolated on white background --ar 9:16 --no zipper, doypack, tapered bottom, wide bag, square shape`,

  box: `Flat bottom box pouch, square block bottom, 5-panel pouch structure, stands perfectly straight like a box, [ZIPPER_TYPE], design theme is [PRODUCT_CATEGORY] packaging, [DESIGN_THEME_COLOR] color palette, [TEXTURE_OR_FINISH], all text must be in English only (no Korean, Chinese, or other non-English characters), product name "[PRODUCT_NAME]", professional studio lighting, 8k resolution, photorealistic, isolated on white background --ar 4:5 --no round bottom, doypack, twisted`,

  tbag: `Two long and narrow T-seal pouches side-by-side, flat lay view on a white background. The pouches have a slender profile with narrow width. The left pouch shows the Front view with "[PRODUCT_NAME]" branding, [DESIGN_THEME_AND_GRAPHICS], smooth surface. The right pouch shows the Back view with product info and a prominent vertical heat-seal line running down the center. Long and narrow pouch shape, designed for single serving [PRODUCT_CATEGORY]. all text must be in English only (no Korean, Chinese, or other non-English characters), product name "[PRODUCT_NAME]", professional studio lighting, 8k resolution, photorealistic. --no stand, box, zipper on top, wide pouch`,

  tbagthick: `Two T-seal pouches side-by-side, flat lay view on a white background. The left pouch shows the Front view with "[PRODUCT_NAME]" branding, [DESIGN_THEME_AND_GRAPHICS], smooth surface. The right pouch shows the Back view with product info and ingredients. Bulky and thick profile pouch shape, filled with volume, rounded edges due to contents. Design theme is [PRODUCT_CATEGORY] packaging. all text must be in English only (no Korean, Chinese, or other non-English characters), product name "[PRODUCT_NAME]", professional studio lighting, 8k resolution, photorealistic. --no stand, box, zipper on top`,

  zipper_3side: `Flat rectangular pouch, 3-side sealed, visible resealable zipper line at top, design theme is [PRODUCT_CATEGORY] packaging, [COLOR_MOOD] print, [TEXTURE_OR_WINDOW], all text must be in English only (no Korean, Chinese, or other non-English characters), product name "[PRODUCT_NAME]", top-down flat lay view, isolated on white background --no stand, bottom gusset, doypack, box shape`,

  mt_bag: `Two center-seal gusset bags (M/T style) lying flat side-by-side on a clean white surface, top-down flat lay view. Both top and bottom edges are completely heat-sealed shut (NOT a stand-up pouch). The pouches have a blocky, rectangular shape with sharp 90-degree corners and crisp angular edges (not rounded), filled with contents like a pack of [MT_CONTENT_TYPE]. Rigid box-like structure with flat planes and defined edges. The left pouch shows the Front view with [MT_FRONT_DESIGN], displaying the full design on the flat front panel. The right pouch shows the Back view with [MT_BACK_DESIGN], and a prominent vertical fin seal (T-seal) running down the center, with visible M-fold gussets on the thick sides. Top edge heat-sealed flat, bottom edge heat-sealed flat - both ends are sealed shut with no opening or stand-up gusset. [MT_TEXTURE] finish. all text must be in English only (no Korean, Chinese, or other non-English characters), professional studio lighting, 8k resolution, photorealistic. --no zipper, spout, handle, stand-up pouch, standing bag, bottom gusset, doypack, rounded corners, soft edges, pillow shape`,

  roll_stock: `A collection of industrial packaging film rolls. Multiple rolls of various sizes are stacked and arranged on a clean surface. Each roll is wound tightly onto a cardboard core, displaying repeating printed designs on glossy plastic or metallic foil material. The designs include [DESIGN_THEME_AND_GRAPHICS], [DESIGN_THEME_COLOR] color palette, and other assorted patterns for [PRODUCT_CATEGORY] packaging, showing vibrant colors. all text must be in English only (no Korean, Chinese, or other non-English characters), product name "[PRODUCT_NAME]" visible on prints. Studio lighting highlights the reflective texture of the film curves. 8k resolution, photorealistic. --no finished pouch, bag, zipper, handle, square bag, flat pouch`,
};

// Unified aliases
export const TEMPLATE_ALIASES: Record<string, string> = {
  // 3side (3면 실링 플랫 파우치)
  '3side': '3side',
  mask: '3side',
  facial: '3side',
  sheet: '3side',
  sachet: '3side',
  flat: '3side',
  packet: '3side',
  // pouch (스탠드업)
  pouch: 'pouch',
  p: 'pouch',
  standup: 'pouch',
  doypack: 'pouch',
  // spout (스파우트)
  spout: 'spout',
  s: 'spout',
  liquid: 'spout',
  nozzle: 'spout',
  // mbag (사이드 거셋)
  mbag: 'mbag',
  m: 'mbag',
  side: 'mbag',
  gusset: 'mbag',
  brick: 'mbag',
  // mbag_slim (슬림 사이드 거셋)
  mbag_slim: 'mbag_slim',
  ms: 'mbag_slim',
  mslim: 'mbag_slim',
  slimbag: 'mbag_slim',
  // box (플랫 바텀)
  box: 'box',
  b: 'box',
  block: 'box',
  square: 'box',
  // tbag (T-seal 좁은형)
  tbag: 'tbag',
  t: 'tbag',
  tseal: 'tbag',
  narrow: 'tbag',
  slim: 'tbag',
  // tbagthick (T-seal 두꺼운형)
  tbagthick: 'tbagthick',
  tt: 'tbagthick',
  thick: 'tbagthick',
  bulky: 'tbagthick',
  cotton: 'tbagthick',
  // zipper_3side (3면 실링 + 지퍼)
  zipper_3side: 'zipper_3side',
  z3: 'zipper_3side',
  zipflat: 'zipper_3side',
  // mt_bag (센터실 거셋 - 김/물티슈 스타일)
  mt_bag: 'mt_bag',
  mt: 'mt_bag',
  mtbag: 'mt_bag',
  centerseal: 'mt_bag',
  finseal: 'mt_bag',
  seaweed: 'mt_bag',
  wipe: 'mt_bag',
  // roll_stock (포장 필름 롤)
  roll_stock: 'roll_stock',
  roll: 'roll_stock',
  rollstock: 'roll_stock',
  film: 'roll_stock',
  filmroll: 'roll_stock',
};

export const getAvailableTemplates = (): string[] =>
  Object.keys(PROMPT_TEMPLATES);

export const getTemplateByName = (name: string): string | null => {
  const normalized = name.toLowerCase();
  const templateKey = TEMPLATE_ALIASES[normalized] ?? normalized;
  return PROMPT_TEMPLATES[templateKey] ?? null;
};

const getRandomItem = <T>(arr: T[]): T =>
  arr[Math.floor(Math.random() * arr.length)];

export const fillPromptVariables = (template: string): string => {
  // MT_BAG 카테고리별 변수
  const mtFrontDesign =
    CATEGORY_TYPE === 'food'
      ? getRandomItem(MT_FRONT_DESIGN_FOOD)
      : getRandomItem(MT_FRONT_DESIGN_BEAUTY);
  const mtBackDesign =
    CATEGORY_TYPE === 'food'
      ? getRandomItem(MT_BACK_DESIGN_FOOD)
      : getRandomItem(MT_BACK_DESIGN_BEAUTY);
  const mtContentType =
    CATEGORY_TYPE === 'food'
      ? getRandomItem(MT_CONTENT_TYPE_FOOD)
      : getRandomItem(MT_CONTENT_TYPE_BEAUTY);

  let result = template
    .replace('[PRODUCT_CATEGORY_MASK]', getRandomItem(PRODUCT_CATEGORY_FOOD_MASK))
    .replace('[PRODUCT_CATEGORY_AND_DESC]', getRandomItem(PRODUCT_CATEGORY))
    .replace('[PRODUCT_CATEGORY]', getRandomItem(PRODUCT_CATEGORY))
    .replace('[COLOR_MOOD]', getRandomItem(COLOR_MOOD))
    .replace('[DESIGN_THEME_COLOR]', getRandomItem(DESIGN_THEME_COLOR))
    .replace(
      '[DESIGN_THEME_AND_GRAPHICS]',
      getRandomItem(DESIGN_THEME_AND_GRAPHICS)
    )
    .replace('[TEXTURE_OR_WINDOW]', getRandomItem(TEXTURE_OR_WINDOW))
    .replace('[TEXTURE_OR_FINISH]', getRandomItem(TEXTURE_OR_FINISH))
    .replace('[ZIPPER_TYPE]', getRandomItem(ZIPPER_TYPE))
    .replace('[MT_FRONT_DESIGN]', mtFrontDesign)
    .replace('[MT_BACK_DESIGN]', mtBackDesign)
    .replace('[MT_CONTENT_TYPE]', mtContentType)
    .replace('[MT_TEXTURE]', getRandomItem(MT_TEXTURE))
    .replaceAll('[PRODUCT_NAME]', getRandomItem(PRODUCT_NAME_BY_CATEGORY));

  if (CATEGORY_TYPE === 'food') {
    result = result.replace(
      /--no\s/,
      '--no mask, facial mask, sheet mask, skincare, cosmetic, '
    );
  }

  return result;
};
